//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaccineManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChildInfo()
        {
            this.Scheduals = new HashSet<Schedual>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Gen_ID { get; set; }
        public System.DateTime DOB { get; set; }
        public string Father_Name { get; set; }
        public string Father_CNIC { get; set; }
        public int UCID { get; set; }
        public int MID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Muhalla Muhalla { get; set; }
        public virtual UnionCouncil UnionCouncil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedual> Scheduals { get; set; }
    }
}
