//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaccineManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public int Parent_Id { get; set; }
        public string Date { get; set; }
    
        public virtual Parent Parent { get; set; }
    }
}
