//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaccineManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedual
    {
        public int Id { get; set; }
        public int Child_Id { get; set; }
        public int Vac_Id { get; set; }
        public Nullable<System.DateTime> Vaccination_Date { get; set; }
        public Nullable<System.DateTime> Next_Date { get; set; }
        public bool Polio { get; set; }
        public bool Inject { get; set; }
    
        public virtual ChildInfo ChildInfo { get; set; }
        public virtual Vaccinator Vaccinator { get; set; }
    }
}
